export const DEV_PATHS = [
  { id: 0, name: "PATHS.TITLES.FRONTEND" },
  { id: 1, name: "PATHS.TITLES.BACKEND" },
  { id: 2, name: "PATHS.TITLES.FULL_STACK" },
  { id: 3, name: "PATHS.TITLES.DEV_OPS" },
  { id: 4, name: "PATHS.TITLES.BLOCKCHAIN" },
  { id: 5, name: "PATHS.TITLES.GAME" },
  { id: 6, name: "PATHS.TITLES.MOBILE" },
  { id: 7, name: "PATHS.TITLES.SECURITY" },
  { id: 8, name: "PATHS.TITLES.DATA" },
  { id: 9, name: "PATHS.TITLES.MACHINE_LEARNING" },
  { id: 10, name: "PATHS.TITLES.AI" },
  { id: 11, name: "PATHS.TITLES.CLOUD" },
  { id: 12, name: "PATHS.TITLES.QA" },
  { id: 13, name: "PATHS.TITLES.UI_UX" },
  { id: 14, name: "PATHS.TITLES.GIS" },
  { id: 15, name: "PATHS.TITLES.CRM" },
  { id: 16, name: "PATHS.TITLES.E_COMMERCE" },
  { id: 17, name: "PATHS.TITLES.ERP" },
  { id: 18, name: "PATHS.TITLES.CMS" },
];
