export const LANGUAGE_LIST = [
  { id: "ENG", name: "LANGUAGES.ENG" },
  { id: "SPA", name: "LANGUAGES.SPA" },
  { id: "CHI", name: "LANGUAGES.CHI" },
  { id: "HIN", name: "LANGUAGES.HIN" },
  { id: "ARA", name: "LANGUAGES.ARA" },
  { id: "POR", name: "LANGUAGES.POR" },
  { id: "BEN", name: "LANGUAGES.BEN" },
  { id: "RUS", name: "LANGUAGES.RUS" },
  { id: "JPN", name: "LANGUAGES.JPN" },
  { id: "PAN", name: "LANGUAGES.PAN" },
  { id: "MAR", name: "LANGUAGES.MAR" },
  { id: "FRA", name: "LANGUAGES.FRA" },
  { id: "DEU", name: "LANGUAGES.DEU" },
  { id: "TEL", name: "LANGUAGES.TEL" },
  { id: "VIE", name: "LANGUAGES.VIE" },
  { id: "KOR", name: "LANGUAGES.KOR" },
  { id: "URD", name: "LANGUAGES.URD" },
  { id: "ITA", name: "LANGUAGES.ITA" },
  { id: "TAM", name: "LANGUAGES.TAM" },
  { id: "TUR", name: "LANGUAGES.TUR" },
  { id: "GUJ", name: "LANGUAGES.GUJ" },
  { id: "POL", name: "LANGUAGES.POL" },
  { id: "UKR", name: "LANGUAGES.UKR" },
  { id: "NLD", name: "LANGUAGES.NLD" },
  { id: "MAL", name: "LANGUAGES.MAL" },
  { id: "THA", name: "LANGUAGES.THA" },
  { id: "SWA", name: "LANGUAGES.SWA" },
  { id: "IND", name: "LANGUAGES.IND" },
  { id: "HEB", name: "LANGUAGES.HEB" },
  { id: "CES", name: "LANGUAGES.CES" },
  { id: "RON", name: "LANGUAGES.RON" },
  { id: "FIL", name: "LANGUAGES.FIL" },
  { id: "SWE", name: "LANGUAGES.SWE" },
  { id: "DAN", name: "LANGUAGES.DAN" },
  { id: "NOR", name: "LANGUAGES.NOR" },
  { id: "FIN", name: "LANGUAGES.FIN" },
  { id: "ZHO", name: "LANGUAGES.ZHO" },
  { id: "YUE", name: "LANGUAGES.YUE" },
  { id: "HAK", name: "LANGUAGES.HAK" },
  { id: "MSA", name: "LANGUAGES.MSA" },
  { id: "MYA", name: "LANGUAGES.MYA" },
  { id: "KAN", name: "LANGUAGES.KAN" },
];

export const LANGUAGE_LEVELS = [
  {
    id: "A1",
    name: "LANGUAGE_LEVELS.A1",
  },
  {
    id: "A2",
    name: "LANGUAGE_LEVELS.A2",
  },
  {
    id: "B1",
    name: "LANGUAGE_LEVELS.B1",
  },
  {
    id: "B2",
    name: "LANGUAGE_LEVELS.B2",
  },
  {
    id: "C1",
    name: "LANGUAGE_LEVELS.C1",
  },
  {
    id: "C2",
    name: "LANGUAGE_LEVELS.C2",
  },
  {
    id: "NATIVE",
    name: "LANGUAGE_LEVELS.NATIVE",
  },
];
