const AUTH_LOGIN = "/login",
  AUTH_REGISTER = "/register",
  DASHBOARD_GET = "/dashboard/",
  EMPLOYMENT_GET = "/employment/",
  EMPLOYMENT_CREATE = "/employment/",
  EMPLOYMENT_UPDATE = "/employment/edit/",
  EMPLOYMENT_REMOVE = "/employment/remove/",
  PROJECTS_GET = "/projects/",
  PROJECTS_CREATE = "/projects/",
  PROJECTS_UPDATE = "/projects/edit/",
  PROJECTS_REMOVE = "/projects/remove/",
  PROFILE_GET = "/profile/",
  PROFILE_UPDATE = "/profile/",
  EDUCATION_GET = "/education/",
  EDUCATION_CREATE = "/education/",
  EDUCATION_UPDATE = "/education/edit/",
  EDUCATION_REMOVE = "/education/remove/",
  EDUCATION_GET_ITEM_DETAILS = "/education/get-details/",
  SETTINGS_GET = "/settings/",
  SETTINGS_UPDATE = "/settings/edit/";

export const ENDPOINTS: any = {
  AUTH_LOGIN,
  AUTH_REGISTER,
  DASHBOARD_GET,
  EMPLOYMENT_GET,
  EMPLOYMENT_CREATE,
  EMPLOYMENT_UPDATE,
  EMPLOYMENT_REMOVE,
  PROJECTS_GET,
  PROJECTS_CREATE,
  PROJECTS_UPDATE,
  PROJECTS_REMOVE,
  PROFILE_GET,
  PROFILE_UPDATE,
  EDUCATION_GET,
  EDUCATION_CREATE,
  EDUCATION_UPDATE,
  EDUCATION_REMOVE,
  EDUCATION_GET_ITEM_DETAILS,
  SETTINGS_GET,
  SETTINGS_UPDATE,
};

export const BASE_URL = "http://localhost:3000";
