const LANDING = "",
  LOGIN = "/login",
  REGISTER = "/register",
  REDIRECT = "/redirect",
  VERIFY_EMAIL = "/verify-email",
  ONBOARDING = "/onboarding",
  TOUR = "/onboarding/tour",
  ROADMAP = "/roadmap",
  EXPERIENCE = "/experience",
  PROJECTS = "/projects",
  EDUCATION = "/education",
  PROFILE = "/profile",
  SETTINGS = "/settings";

export const ROUTES: any = {
  LANDING,
  LOGIN,
  REGISTER,
  REDIRECT,
  VERIFY_EMAIL,
  ONBOARDING,
  TOUR,
  ROADMAP,
  EXPERIENCE,
  PROJECTS,
  EDUCATION,
  PROFILE,
  SETTINGS,
};
