const LANDING = "",
  LOGIN = "/login",
  REGISTER = "/register",
  REDIRECT = "/redirect",
  WELCOME = "/welcome",
  DASHBOARD = "/dashboard",
  EMPLOYMENT = "/employment",
  PROJECTS = "/projects",
  EDUCATION = "/education",
  PROFILE = "/profile",
  SETTINGS = "/settings";

export const ROUTES: any = {
  LANDING,
  LOGIN,
  REGISTER,
  REDIRECT,
  WELCOME,
  DASHBOARD,
  EMPLOYMENT,
  PROJECTS,
  EDUCATION,
  PROFILE,
  SETTINGS,
};
