export const DEV_ROLES = [
  "PROFILE.ROLES.FRONTEND",
  "PROFILE.ROLES.BACKEND",
  "PROFILE.ROLES.FULL_STACK",
  "PROFILE.ROLES.DEV_OPS",
  "PROFILE.ROLES.BLOCKCHAIN",
  "PROFILE.ROLES.GAME",
  "PROFILE.ROLES.APP",
  "PROFILE.ROLES.SECURITY",
];
