export const DEV_PATHS = [
  "PROFILE.PATHS.FRONTEND",
  "PROFILE.PATHS.BACKEND",
  "PROFILE.PATHS.FULL_STACK",
  "PROFILE.PATHS.DEV_OPS",
  "PROFILE.PATHS.BLOCKCHAIN",
  "PROFILE.PATHS.GAME",
  "PROFILE.PATHS.APP",
  "PROFILE.PATHS.SECURITY",
];
